apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: bWljcm9zZXJ2aWNlcy1yZHMuY3U5ZXFvMGM0ZjV3LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_user: YWRtaW4=
  db_password: U2FpMTIzNDU=
